### ISSUE TITLE
PlatformIO: Unknown board ID 'wiscore_rak4631'

### ISSUE THREAD

**Issue by karamo** [icssw-org/MeshCom-Firmware#32]
**Describe the bug**
PlatformIO kann nicht kompilieren, da diese Fehlermeldung kommt:

```
Resolving wiscore_rak4631 dependencies...
UnknownBoard: Unknown board ID 'wiscore_rak4631'
```

**Additional context**

**VSC**
Version: 1.87.2 (user setup)  
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6  
Date: 2024-03-08T15:20:17.278Z  
Electron: 27.3.2  
ElectronBuildId: 26836302  
Chromium: 118.0.5993.159  
Node.js: 18.17.1  
V8: 11.8.172.18-electron.0  
OS: Windows_NT x64 10.0.19045  

**PlatformIO**  
Core 6.1.14·Home 3.4.4

**Comment by rainerfritz** [comment]
Please install the Nordic nRF52 Framework Version 9.6.0 under Platforms.
Then follow these installation instructions:
https://github.com/RAKWireless/WisBlock/blob/master/PlatformIO/README.md

**Comment by karamo** [comment]
ok, behoben ... close Issue
