### ISSUE TITLE
T-DECK not supported ?

### ISSUE THREAD

**Issue by ok1cdj** [icssw-org/MeshCom-Firmware#42]
Hello, is T-DECK still supported ? 

73 Ondra OK1CDJ

**Comment by oe1kbc** [comment]
Hi Ondra,

Yes shure,  and we will work on updates after summer break.

 

73 de Kurt

OE1KBC

 

Ing. Kurt Baumann
Vize-President
ICSSW AMSAT-OE
Höhenstrasse 65
3040 Neulengbach
Austria
T: +43 699 1200 3520
M:  ***@***.***> ***@***.***
H:  <https://icssw.org> https://icssw.org

 

Von: Ondrej Kolonicny ***@***.***> 
Gesendet: Freitag, 12. Juli 2024 11:03
An: icssw-org/MeshCom-Firmware ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [icssw-org/MeshCom-Firmware] T-DECK not supported ? (Issue #42)

 

Hello, is T-DECK still supported ?

73 Ondra OK1CDJ

**Comment by ok1cdj** [comment]
Hello Kurt, which ENV is for T-DECK. Firmware is not available in Webflasher.

73 Ondra OK1CDJ

**Comment by rainerfritz** [comment]
Hi!

The T-Deck should work now with the online flasher.
Release 4.28b and choose T-Deck.

BR
Rainer



Ondrej Kolonicny ***@***.***> schrieb am Fr. 12. Juli 2024 um
11:35:

**Comment by ok1cdj** [comment]
ok, installed 4.28b without problem..
TNX

**Comment by ok1cdj** [comment]
Is there source code for T-DECK available, i think is not part of this FW.

**Comment by oe1kbc** [comment]
Hi,No Firmware Source in the Moment but we are working on this to do it in the Future.73 de KurtOE1KBCAm 01.08.2024 um 15:58 schrieb Ondrej Kolonicny ***@***.***>:﻿
Is there source code for T-DECK available, i think is not part of this FW.
