### ISSUE TITLE
No Transmissions on Mobil with GPS and TRACK on

### ISSUE THREAD

**Issue by whallmann** [icssw-org/MeshCom-Firmware#62]
**Conditions**

- TBEAM (no APX)
- Version 434.c 
- Wifi on - but on in Range of Home
- Buttons via BT APP checked if activ: DISPLAY, GPS, MESH, BUTTON, TRACK, WEBSERVER (Gateway off)
- Display shows: Pos, GPS fix 9 
- Start tour.  DEBUGING activ captioned to putty.log

**Describe the bug**
Software seems not to TX anything, no 433.175 nor 433.775 APRS (for this Receivers are in Range

**To Reproduce**
Can reproduce this every tour with the car.
On only one Tour some days earlier, it works fine as expected. But only ones. Difference to actual tours. As it works ones, I started the T-Beam an hour earlier with a batterypack, took this to the car and go around.

**Serial Log**
[rückfahrt_putty.log](https://github.com/user-attachments/files/18266019/ruckfahrt_putty.log)

**Screenshots**
![Screenshot_20241228-111428](https://github.com/user-attachments/assets/4a993eb9-f590-46ba-9bfc-c7f6c4a3ad76)
![PXL_20241228_101322341](https://github.com/user-attachments/assets/4560f462-bb81-4103-a676-52d80f16893f)

**Smartphone (please complete the following information):**
 - Device: T-Beam / Pixel8pro
 - OS: Android15
 - App Version 4.20

**Additional context**
I already took a look into the trace and wounder why this line always dont see any old coordinates.  I guess this seems to be the problem.  No move, no TX?

**11:47:07 POSINFO one-shot set - direction_diff:6 last_lat:0.0 last_lon:0.0**

**Comment by rainerfritz** [comment]
With Re-Flashing and Erase the problem was solfed.
